#!/usr/bin/env python3
"""PromptBuilder field-contract tests (2026-08-18).

Covers:
- command prompts only render declared fields (CLI global-flag super-set
  leak, H2)
- workflow prompts strip `(default: X)` annotations so wizard/CLI keys
  match the declared field set
- empty/False/None values are skipped
- unknown keys are filtered out when a declared set is provided

Run:
    python -m unittest cli/tests/test_prompt_builder.py
"""

import re
import sys
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from cli.services.prompt_builder import PromptBuilder  # noqa: E402


def _template_inputs(prompt):
    """The ## Inputs block generated by the template (not the definition)."""

    idx = prompt.rfind("## Inputs")

    if idx < 0:
        return ""

    body = prompt[idx:]

    body = body.split("---", 1)[0]

    body = body.split("Begin execution", 1)[0]

    return body.replace("## Inputs", "").strip()


class TestFieldContract(unittest.TestCase):

    def setUp(self):
        self.builder = PromptBuilder()

    def test_command_filters_undeclared_fields(self):
        # scan 专用字段注入 trace（CLI 全局 flag 超集泄漏，H2）
        prompt = self.builder.build(
            "trace",
            {
                "Project ID": "demo",
                "Code Reference": "foo",
                "Operation": "search",
                "Keep Results": False,
                "agent": "x",
            },
        )
        inputs = _template_inputs(prompt)
        self.assertIn("Project ID: demo", inputs)
        self.assertIn("Code Reference: foo", inputs)
        self.assertNotIn("Operation", inputs)
        self.assertNotIn("Keep Results", inputs)
        self.assertNotIn("agent", inputs)

    def test_workflow_strips_default_annotation(self):
        # Base Branch (default: master) 声明 vs Base Branch 传入
        prompt = self.builder.build(
            "change-impact",
            {
                "Projects": "a,b",
                "Code Reference": "x",
                "Base Branch": "main",
            },
        )
        inputs = _template_inputs(prompt)
        self.assertIn("Base Branch: main", inputs)
        self.assertNotIn("(default:", inputs)

    def test_empty_and_false_values_skipped(self):
        prompt = self.builder.build(
            "scan",
            {
                "Operation": "search",
                "Projects": "",
                "Code Reference": "foo",
                "Keep Results": False,
            },
        )
        inputs = _template_inputs(prompt)
        self.assertIn("Operation: search", inputs)
        self.assertIn("Code Reference: foo", inputs)
        self.assertNotIn("Projects:", inputs)
        self.assertNotIn("Keep Results", inputs)

    def test_unknown_workflow_keys_filtered(self):
        prompt = self.builder.build(
            "release",
            {
                "Workspace ID": "w1",
                "Release Version": "1.0",
                "totally_unrelated": "x",
            },
        )
        inputs = _template_inputs(prompt)
        self.assertIn("Workspace ID: w1", inputs)
        self.assertIn("Release Version: 1.0", inputs)
        self.assertNotIn("totally_unrelated", inputs)


if __name__ == "__main__":
    unittest.main()
