#!/usr/bin/env python3
"""PromptBuilder field-contract tests (2026-08-18).

Covers:
- command prompts only render declared fields (CLI global-flag super-set
  leak, H2)
- workflow prompts strip `(default: X)` annotations so wizard/CLI keys
  match the declared field set
- empty/False/None values are skipped
- unknown keys are filtered out when a declared set is provided

Run:
    python -m unittest cli/tests/test_prompt_builder.py
"""

import re
import sys
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from cli.services.prompt_builder import PromptBuilder  # noqa: E402


def _template_inputs(prompt):
    """The ## Inputs block generated by the template (not the definition)."""

    idx = prompt.rfind("## Inputs")

    if idx < 0:
        return ""

    body = prompt[idx:]

    body = body.split("---", 1)[0]

    body = body.split("Begin execution", 1)[0]

    return body.replace("## Inputs", "").strip()


class TestFieldContract(unittest.TestCase):

    def setUp(self):
        self.builder = PromptBuilder()

    def test_command_filters_undeclared_fields(self):
        # scan 专用字段注入 trace（CLI 全局 flag 超集泄漏，H2）
        prompt = self.builder.build(
            "trace",
            {
                "Project ID": "demo",
                "Code Reference": "foo",
                "Operation": "search",
                "Keep Results": False,
                "agent": "x",
            },
        )
        inputs = _template_inputs(prompt)
        self.assertIn("Project ID: demo", inputs)
        self.assertIn("Code Reference: foo", inputs)
        self.assertNotIn("Operation", inputs)
        self.assertNotIn("Keep Results", inputs)
        self.assertNotIn("agent", inputs)

    def test_workflow_strips_default_annotation(self):
        # Base Branch (default: master) 声明 vs Base Branch 传入
        prompt = self.builder.build(
            "change-impact",
            {
                "Projects": "a,b",
                "Code Reference": "x",
                "Base Branch": "main",
            },
        )
        inputs = _template_inputs(prompt)
        self.assertIn("Base Branch: main", inputs)
        self.assertNotIn("(default:", inputs)

    def test_empty_and_false_values_skipped(self):
        prompt = self.builder.build(
            "scan",
            {
                "Operation": "search",
                "Projects": "",
                "Code Reference": "foo",
                "Keep Results": False,
            },
        )
        inputs = _template_inputs(prompt)
        self.assertIn("Operation: search", inputs)
        self.assertIn("Code Reference: foo", inputs)
        self.assertNotIn("Projects:", inputs)
        self.assertNotIn("Keep Results", inputs)

    def test_unknown_workflow_keys_filtered(self):
        prompt = self.builder.build(
            "release",
            {
                "Workspace ID": "w1",
                "Release Version": "1.0",
                "totally_unrelated": "x",
            },
        )
        inputs = _template_inputs(prompt)
        self.assertIn("Workspace ID: w1", inputs)
        self.assertIn("Release Version: 1.0", inputs)
        self.assertNotIn("totally_unrelated", inputs)

    def test_root_placeholders_resolved_at_render(self):
        # P30：根路径占位符渲染期白名单替换（仅 paths() 根键）
        prompt = self.builder.build("dev-setup", {})
        # 根键被替换为绝对路径
        self.assertNotIn("{workspace_root}", prompt)
        self.assertNotIn("{repository_root}", prompt)
        # 运行期键保持符号（白名单外）
        self.assertIn("{project_id}", prompt)
        self.assertIn("{service_id}", prompt)

    def test_root_placeholders_fallback_on_paths_failure(self):
        # P30：paths() 解析失败 → 保留原文（与现状一致）
        import cli.services.environment as env_mod

        orig = env_mod.paths

        def boom(root, name="local"):
            raise RuntimeError("env broken")

        env_mod.paths = boom
        try:
            prompt = self.builder.build("bootstrap", {})
            self.assertIn("config/environments", prompt)
        finally:
            env_mod.paths = orig

    def test_r3_full_runtime_switch(self):
        # Q2/R3：AIC_FULL_RUNTIME=1 → 内嵌全量 runtime；默认骨架
        import os

        skel = self.builder.build("release", {})
        self.assertIn("Full runtime template", skel)

        os.environ["AIC_FULL_RUNTIME"] = "1"
        try:
            full = self.builder.build("release", {})
        finally:
            del os.environ["AIC_FULL_RUNTIME"]

        self.assertNotIn("Full runtime template", full)
        self.assertGreater(len(full), len(skel))
        self.assertIn("# Phase 1", full)

    def test_frontmatter_stripped_from_definition(self):
        # 2026-08-25 优化：workflow frontmatter（机器契约）不整段嵌入提示词
        prompt = self.builder.build("prepare", {})
        head = prompt.split("Begin execution", 1)[0]
        self.assertNotIn("name: prepare", head)
        self.assertNotIn("workflow:\n", head)
        # 正文八节保留
        self.assertIn("## Purpose", head)
        self.assertIn("## Exit Criteria", head)

    def test_capabilities_before_task_anchor(self):
        # 2026-08-25 优化：能力段注入到 # Task 之前（执行前须知）
        prompt = self.builder.build("prepare", {})
        task_idx = prompt.find("# Task")
        caps_idx = prompt.find("## Optional External Capabilities")
        self.assertNotEqual(caps_idx, -1)
        self.assertLess(caps_idx, task_idx)

    def test_runtime_skeleton_matches_level2_phase(self):
        # 2026-08-25 优化：runtime-prepare 用 ## Phase N 二级标题，
        # 骨架化必须匹配（此前仅一级 # Phase，prepare 骨架为空）
        prompt = self.builder.build("prepare", {})
        self.assertIn("## Phase 1 — Requirement Collection", prompt)
        self.assertIn("Full runtime template:", prompt)

    def test_command_definition_strips_frontmatter(self):
        # command 定义同样剥离 frontmatter（name/description 机器契约）
        prompt = self.builder.build("maintain", {})
        head = prompt.split("Begin execution", 1)[0]
        self.assertNotIn("description: 初始化", head)
        # 中文 desc 不在 command 定义区（被 frontmatter 剥离）
        self.assertNotIn("初始化/校验环境配置", head)

    def test_runtime_section_points_to_skeleton(self):
        # 2026-08-25 优化 2：workflow 正文 ## Runtime 节不再重复相对路径，
        # 改为指向骨架（源文件不动，渲染层去重）
        prompt = self.builder.build("prepare", {})
        run_sec = prompt.split("## Preconditions", 1)[0]
        self.assertIn("See the Runtime Skeleton below", run_sec)
        # 相对路径不出现（源文件是 templates/runtime/runtime-prepare.md）
        self.assertNotIn("- templates/runtime/runtime-prepare.md", run_sec)

    def test_skeleton_heading_and_list_item_merge(self):
        # 2026-08-25 优化 1+3：骨架带 ## Runtime Skeleton 标题；
        # 引言行（Collect:）合并首个列表项，避免只剩动词
        prompt = self.builder.build("prepare", {})
        self.assertIn("## Runtime Skeleton", prompt)
        self.assertIn("Collect:\n    - User Requirements", prompt)

    def test_command_path_unaffected_by_runtime_dedupe(self):
        # command 无 ## Runtime 节，去重与骨架逻辑不触碰 command 路径
        prompt = self.builder.build("maintain", {})
        self.assertNotIn("## Runtime", prompt)
        self.assertNotIn("Runtime Skeleton", prompt)

    def test_runtime_skeleton_merges_base_keep(self):
        """R1（P45 缺陷修复）：runtime 模板 `Extends: runtime-base.md` 的
        @keep 级机制（P45 语言门禁步骤）必须进入骨架化 prompt。

        回归：曾只骨架化 runtime-<name>.md 自身，base 机制对 AI 不可见
        （develop/prepare 日志实读清单均无 runtime-base.md）。
        """
        prompt = self.builder.build("develop", {})
        self.assertIn(
            "language-gate",
            prompt,
            "base @keep 机制（P45 语言门禁）应出现在 develop 的 runtime 骨架中",
        )
        self.assertIn(
            "Before presenting, the Runtime runs the language gate",
            prompt,
        )



if __name__ == "__main__":
    unittest.main()
