#!/usr/bin/env python3
"""Skill-optimizer action handlers (P11 absorption).

Three lightweight, AI-assisted actions added on top of the four atomic
optimization modes, each following the same discipline as the core
optimizer: candidate-first, snapshot-versioned, human-decides.

  * augment          — demo-augment (DSPy BootstrapFewShot idea): turn
                       successful execution traces/examples into a
                       "## Examples" section in SKILL.md.
  * validate         — held-out gating (SkillOpt idea): run a held-out
                       benchmark (generated by skill-benchmark-generator)
                       against the latest candidate vs. current baseline
                       and report PASS/FAIL + accept/reject recommendation.
  * tune-description — description tuning (Claude skill-creator idea):
                       evaluate frontmatter description against routing
                       criteria and propose a rewrite.

All three are read-mostly: they PROPOSE a change (candidate content +
snapshot), never auto-accept. Adoption goes through the existing
`accept` action, which the human operator invokes deliberately.
"""

import json
import logging
import re
from pathlib import Path
from typing import Optional

from core import RealLLMClient

logger = logging.getLogger(__name__)

EXAMPLES_HEADING_RE = re.compile(r"(?im)^##\s*Examples\s*$")
FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---", re.DOTALL)


def _load_llm() -> Optional[RealLLMClient]:
    try:
        return RealLLMClient()
    except ValueError as e:
        logger.error(str(e))
        return None


def _read_skill(skill_md: Path) -> str:
    return skill_md.read_text(encoding="utf-8")


def _write_skill(skill_md: Path, content: str) -> None:
    skill_md.write_text(content, encoding="utf-8")


# ---------------------------------------------------------------------------
# Action 1: augment (demo-augment)
# ---------------------------------------------------------------------------

def run_augment(input_path: Path, demos_file: Optional[Path]) -> int:
    """Inject successful execution examples into SKILL.md as '## Examples'.

    demos_file: JSON array of {task, approach, result} (or any dict with a
    'task' field; 'approach'/'result' optional). If omitted, prints guidance.

    Proposes a new snapshot containing the augmented SKILL.md; does NOT
    adopt it. Return 0 on success.
    """
    llm = _load_llm()
    if not llm:
        return 1

    skill_dir = input_path.parent if input_path.is_file() else input_path
    skill_md = skill_dir / "SKILL.md"
    if not skill_md.exists():
        logger.error(f"SKILL.md not found in: {skill_dir}")
        return 1

    if not demos_file or not demos_file.exists():
        logger.error("augment requires --demos <demos.json> "
                     "(JSON array of {task, approach, result})")
        return 1

    try:
        demos = json.loads(demos_file.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        logger.error(f"Invalid demos JSON: {e}")
        return 1
    if not isinstance(demos, list) or not demos:
        logger.error("demos.json must be a non-empty array")
        return 1

    skill_content = _read_skill(skill_md)

    SYSTEM_EXAMPLES = (
        "You are improving an agent Skill definition. The Skill's SKILL.md\n"
        "content is provided below. You are given a set of successful\n"
        "execution examples (task / approach / result) from real usage.\n\n"
        "Your job: produce a concise '## Examples' section (Markdown) that\n"
        "distills the best 2-3 of these real examples into reusable guidance.\n"
        "Each example must show: the concrete task, the correct approach, and\n"
        "the expected outcome. Keep each example short (5-10 lines). Do NOT\n"
        "invent examples beyond the data. If a '## Examples' section already\n"
        "exists, propose an UPDATED version (replace or extend it).\n\n"
        "Return ONLY the '## Examples' section markdown, no preamble.\n\n"
    )

    prompt = (
        f"===== DEMOS (JSON) =====\n{json.dumps(demos, ensure_ascii=False, indent=2)}\n\n"
        f"===== CURRENT SKILL.md =====\n{skill_content[:8000]}"
    )
    section = (llm(prompt, system=SYSTEM_EXAMPLES) or "").strip()

    if not section:
        logger.error("LLM returned empty Examples section; aborting")
        return 1
    if not section.startswith("## Examples"):
        section = "## Examples\n\n" + section.lstrip("#").strip()

    # Replace existing Examples section or append before end
    if EXAMPLES_HEADING_RE.search(skill_content):
        new_content = EXAMPLES_HEADING_RE.sub(section + "\n", skill_content, count=1)
    else:
        new_content = skill_content.rstrip() + "\n\n" + section + "\n"

    return _propose_candidate(
        skill_dir, skill_md, new_content,
        mode="augment",
        reason="demo-augment: 成功示例沉淀为 Examples 区 (P11)",
    )


# ---------------------------------------------------------------------------
# Action 2: validate (held-out gating)
# ---------------------------------------------------------------------------

def run_validate(input_path: Path, benchmark_file: Optional[Path]) -> int:
    """Held-out validation: latest candidate vs. current baseline.

    benchmark_file: JSON array of {task, expected_outcome} (the output of
    skill-benchmark-generator). The LLM judges whether the current baseline
    and the latest snapshot each produce the expected outcome per task,
    then reports pass rates and an accept/reject recommendation.

    Read-only: does not modify the skill or snapshots. Return 0 on success.
    """
    llm = _load_llm()
    if not llm:
        return 1

    skill_dir = input_path.parent if input_path.is_file() else input_path
    skill_md = skill_dir / "SKILL.md"
    if not skill_md.exists():
        logger.error(f"SKILL.md not found in: {skill_dir}")
        return 1

    if not benchmark_file or not benchmark_file.exists():
        logger.error("validate requires --benchmark <benchmark.json> "
                     "(JSON array of {task, expected_outcome})")
        return 1

    try:
        tasks = json.loads(benchmark_file.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        logger.error(f"Invalid benchmark JSON: {e}")
        return 1
    if not isinstance(tasks, list) or not tasks:
        logger.error("benchmark.json must be a non-empty array")
        return 1

    # Normalize generator-native formats to (task, expected_outcome) pairs.
    # Supported shapes:
    #   routing item   -> {query, expectedSkills, routingIntent?, routingAnchors?}
    #   outcome item   -> {skill?, skillVersion?, standardAnswer, rootCauses?, keyActions?}
    #   minimal item   -> {task, expected_outcome}
    normalized = []
    for item in tasks:
        if not isinstance(item, dict):
            continue
        if "task" in item and "expected_outcome" in item:
            normalized.append((item["task"], item["expected_outcome"]))
        elif "query" in item and "expectedSkills" in item:
            norm = {
                "task": item["query"],
                "expected_outcome": item["expectedSkills"],
            }
            for k in ("routingIntent", "routingAnchors"):
                if item.get(k):
                    norm[k] = item[k]
            normalized.append((item["query"], item["expectedSkills"]))
        elif "standardAnswer" in item:
            norm = {"task": item.get("sourceScenario") or "skill outcome"}
            expected = {"standardAnswer": item["standardAnswer"]}
            if item.get("rootCauses"):
                expected["rootCauses"] = item["rootCauses"]
            if item.get("keyActions"):
                expected["keyActions"] = item["keyActions"]
            normalized.append((norm["task"], expected))

    if not normalized:
        logger.error("benchmark.json contains no recognizable items "
                     "(expected routing/outcome/minimal shapes)")
        return 1
    tasks = [{"task": t, "expected_outcome": e} for t, e in normalized]

    # Current baseline = live SKILL.md; candidate = latest snapshot version
    from snapshot_manager import SnapshotManager
    sm = SnapshotManager(skill_dir)
    latest = sm.get_latest_version()
    if not latest:
        logger.error("No snapshot versions found; nothing to validate")
        return 1

    snap_skill = sm.snapshots_dir / latest / "SKILL.md"
    candidate_content = (
        snap_skill.read_text(encoding="utf-8") if snap_skill.exists() else None
    )
    baseline_content = _read_skill(skill_md)

    SYSTEM_VALIDATOR = (
        "You are a held-out validator for an agent Skill. For each task\n"
        "below, decide whether the Skill definition would produce the\n"
        "expected outcome. Answer strictly PASS or FAIL per task, with a\n"
        "one-line reason. End with 'PASS RATE: X/Y'.\n\n"
    )

    def judge(content: str, label: str) -> dict:
        prompt = (
            f"===== SKILL ({label}) =====\n{content[:8000]}\n\n"
            f"===== TASKS =====\n{json.dumps(tasks, ensure_ascii=False, indent=2)}"
        )
        out = (llm(prompt, system=SYSTEM_VALIDATOR) or "").strip()
        # Count PASS/FAIL on task lines only; exclude the trailing
        # "PASS RATE: X/Y" summary line (would double-count).
        body = "\n".join(
            ln for ln in out.splitlines()
            if "PASS RATE" not in ln.upper()
        )
        passed = len(re.findall(r"\bPASS\b", body, re.IGNORECASE))
        failed = len(re.findall(r"\bFAIL\b", body, re.IGNORECASE))
        return {"raw": out, "passed": passed, "failed": failed}

    print("\n" + "=" * 60)
    print("🧪 Held-out 验证 (SkillOpt 门控思想 / P11)")
    print("=" * 60)
    baseline = judge(baseline_content, "baseline (current)")
    print(f"\n[baseline] 当前基线  PASS={baseline['passed']} FAIL={baseline['failed']}")

    candidate = None
    if candidate_content and candidate_content != baseline_content:
        candidate = judge(candidate_content, f"candidate ({latest})")
        print(f"[candidate] 快照 {latest}  PASS={candidate['passed']} FAIL={candidate['failed']}")
    else:
        print(f"[candidate] 无独立候选（快照 {latest} 与基线一致），跳过对比")

    print("\n---- baseline 明细 ----")
    print(baseline["raw"][:1500])
    if candidate:
        print("\n---- candidate 明细 ----")
        print(candidate["raw"][:1500])

    # Recommendation (candidate exists and differs)
    if candidate:
        b_rate = baseline["passed"] / max(1, baseline["passed"] + baseline["failed"])
        c_rate = candidate["passed"] / max(1, candidate["passed"] + candidate["failed"])
        print("\n" + "=" * 60)
        if c_rate >= b_rate:
            print(f"✅ 建议: ACCEPT {latest} (通过率 {c_rate:.0%} >= 基线 {b_rate:.0%})")
            print("   采纳请运行: opt.sh --action accept --input <skill_dir>")
        else:
            print(f"⚠️ 建议: REJECT {latest} (通过率 {c_rate:.0%} < 基线 {b_rate:.0%})")
            print("   保留基线; 候选可回滚: opt.sh --action revert --target-version <v> --input <skill_dir>")
        print("=" * 60)
    return 0


# ---------------------------------------------------------------------------
# Action 3: tune-description
# ---------------------------------------------------------------------------

def run_tune_description(input_path: Path, routing_report: Optional[Path]) -> int:
    """Evaluate the frontmatter description for routing quality and
    propose a rewrite.

    Optionally takes a routing-benchmark report (JSON) with fields like
    {hit_rate, miss_examples} to ground the critique in real routing data.
    Proposes a snapshot with the rewritten description; adoption stays
    with the human via accept.
    """
    llm = _load_llm()
    if not llm:
        return 1

    skill_dir = input_path.parent if input_path.is_file() else input_path
    skill_md = skill_dir / "SKILL.md"
    if not skill_md.exists():
        logger.error(f"SKILL.md not found in: {skill_dir}")
        return 1

    skill_content = _read_skill(skill_md)
    fm = FRONTMATTER_RE.search(skill_content)
    if not fm:
        logger.error("No YAML frontmatter found; cannot tune description")
        return 1
    current_desc = ""
    dm = re.search(r"^description:\s*(?:\>\s*\n)?\s*(.+)$", fm.group(1), re.MULTILINE)
    if dm:
        current_desc = dm.group(1).strip()

    routing = ""
    if routing_report and routing_report.exists():
        try:
            routing = routing_report.read_text(encoding="utf-8")[:3000]
        except OSError:
            routing = ""

    SYSTEM_TUNE_DESC = (
        "You are tuning the frontmatter description of an agent Skill.\n"
        "The description is what a router/agent reads to decide whether to\n"
        "invoke this Skill. A good description: names the concrete trigger\n"
        "scenario, uses action verbs, includes the domain vocabulary the\n"
        "router would see, and avoids vague words like 'help'/'assist'.\n\n"
        "Critique the current description, then propose a rewritten one\n"
        "(max 800 chars, keep the YAML structure). Return:\n"
        "1) 2-3 bullet critiques\n"
        "2) '---' separator\n"
        "3) the new description value only\n\n"
    )

    prompt = (
        f"CURRENT DESCRIPTION: {current_desc!r}\n"
        + (f"\nROUTING REPORT:\n{routing}\n" if routing else "\n(no routing report provided)\n")
        + f"\nSKILL.md head:\n{skill_content[:3000]}"
    )
    out = (llm(prompt, system=SYSTEM_TUNE_DESC) or "").strip()

    new_desc = None
    parts = out.split("---")
    if len(parts) >= 2:
        new_desc = parts[-1].strip()
    if not new_desc:
        logger.error("LLM returned no usable description; aborting")
        return 1
    new_desc = new_desc.strip("`\"").strip()

    # Apply to frontmatter only
    new_content = skill_content
    if dm:
        new_content = (
            skill_content[: fm.start()]
            + skill_content[fm.start(): fm.end()].replace(
                dm.group(0), f"description: {new_desc}"
            )
            + skill_content[fm.end():]
        )
    else:
        # No description field yet: insert after the frontmatter 'name:' line
        fm_text = fm.group(1)
        if re.search(r"(?m)^name:\s*\S+", fm_text):
            new_fm = re.sub(
                r"(?m)^(name:\s*\S+)$",
                r"\1\ndescription: " + new_desc,
                fm_text,
                count=1,
            )
        else:
            new_fm = "description: " + new_desc + "\n" + fm_text
        new_content = (
            skill_content[: fm.start()]
            + "---\n" + new_fm + "\n---"
            + skill_content[fm.end():]
        )

    print("\n" + "=" * 60)
    print("🎯 description 调优 (Claude skill-creator 思想 / P11)")
    print("=" * 60)
    print(f"[现状] {current_desc!r}")
    print(f"[建议] {new_desc!r}")
    print("\n----- LLM 评估 -----")
    print(out[:1200])
    print("=" * 60)
    print("采纳请运行: opt.sh --action accept --input <skill_dir>")

    return _propose_candidate(
        skill_dir, skill_md, new_content,
        mode="description",
        reason="description 调优 (P11)",
    )


# ---------------------------------------------------------------------------
# Shared candidate-snapshot helper
# ---------------------------------------------------------------------------

def _propose_candidate(
    skill_dir: Path,
    skill_md: Path,
    new_content: str,
    mode: str,
    reason: str,
) -> int:
    """Write the proposed content into a NEW snapshot version without
    touching the live skill dir. Returns 0 on success."""
    from snapshot_manager import SnapshotManager

    sm = SnapshotManager(skill_dir)
    new_version = sm.create_snapshot(mode=mode, reason=reason, source="auto")
    # create_snapshot copies current skill files; overwrite its SKILL.md
    dest = sm.snapshots_dir / new_version / "SKILL.md"
    dest.write_text(new_content, encoding="utf-8")

    logger.info(f"候选已写入快照: {new_version} (未采纳)")
    logger.info(f"  查看差异: uv run python scripts/diff_viewer.py "
                f"--snapshots {sm.snapshots_dir} --title \"{skill_md.parent.name}\"")
    logger.info(f"  采纳: ./scripts/opt.sh --action accept --input {skill_dir}")
    logger.info(f"  回滚: ./scripts/opt.sh --action revert --target-version <v> --input {skill_dir}")
    return 0
